### ISSUE TITLE
Re-licensing 

### ISSUE THREAD

**Issue by jimbok8** [Naoghuman/lib-preferences#28]
Would you consider re-licensing this to a more permissive licence please; e.g. Apache or MIT?

**Comment by Naoghuman** [comment]
Hi @jimbok8,
would you like to told me why you need another license?
All my libraries are GPL-3.0. So when I would change the license I must do it in all my projects here in GitHub.

Background informations about the licensing:
* https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

JavaFX libraries and their licensing:
* ControlsFX = BSD 3-clause
* FontAwesomeFX = Apache License, Version 2.0
* Do more research...

**Comment by Naoghuman** [comment]
Since no feedback to my question I close this issue.
